plugins {
    id 'com.android.application'
}

android {
    namespace 'com.houedanou.fatloss.wear'
    compileSdk 34

    defaultConfig {
        applicationId 'com.houedanou.fatloss.wear'
        minSdk 30
        targetSdk 33
        versionCode 2
        versionName '1.1'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    // Aucune dépendance externe : WebView + capteurs du framework Android uniquement.
}
